// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/healthcheck.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get health status of services.
type GetHealthCheckRequest struct {
	// Check only the http service
	HttpOnly             bool     `protobuf:"varint,1,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckRequest) Reset()         { *m = GetHealthCheckRequest{} }
func (m *GetHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckRequest) ProtoMessage()    {}
func (*GetHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e97722440bc80f4, []int{0}
}

func (m *GetHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckRequest.Merge(m, src)
}
func (m *GetHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckRequest.Size(m)
}
func (m *GetHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckRequest proto.InternalMessageInfo

func (m *GetHealthCheckRequest) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

// Health status of services.
type GetHealthCheckResponse struct {
	// The status of the relevant sub services.
	Reports []*HealthCheckReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	// An exception if an error occurred during processing request.
	Exception            *Exception `protobuf:"bytes,2,opt,name=exception,proto3" json:"exception,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetHealthCheckResponse) Reset()         { *m = GetHealthCheckResponse{} }
func (m *GetHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckResponse) ProtoMessage()    {}
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e97722440bc80f4, []int{1}
}

func (m *GetHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckResponse.Unmarshal(m, b)
}
func (m *GetHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckResponse.Merge(m, src)
}
func (m *GetHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckResponse.Size(m)
}
func (m *GetHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckResponse proto.InternalMessageInfo

func (m *GetHealthCheckResponse) GetReports() []*HealthCheckReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *GetHealthCheckResponse) GetException() *Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

// Health check status of an individual service.
type HealthCheckReport struct {
	// Timestamp of when the report was generated (RFC3339).
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Status of the service.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Name of the service.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Version of the service.
	ServiceVersion       string   `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReport) Reset()         { *m = HealthCheckReport{} }
func (m *HealthCheckReport) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReport) ProtoMessage()    {}
func (*HealthCheckReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e97722440bc80f4, []int{2}
}

func (m *HealthCheckReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReport.Unmarshal(m, b)
}
func (m *HealthCheckReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReport.Marshal(b, m, deterministic)
}
func (m *HealthCheckReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReport.Merge(m, src)
}
func (m *HealthCheckReport) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReport.Size(m)
}
func (m *HealthCheckReport) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReport.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReport proto.InternalMessageInfo

func (m *HealthCheckReport) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *HealthCheckReport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthCheckReport) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *HealthCheckReport) GetServiceVersion() string {
	if m != nil {
		return m.ServiceVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHealthCheckRequest)(nil), "common.GetHealthCheckRequest")
	proto.RegisterType((*GetHealthCheckResponse)(nil), "common.GetHealthCheckResponse")
	proto.RegisterType((*HealthCheckReport)(nil), "common.HealthCheckReport")
}

func init() { proto.RegisterFile("common/healthcheck.proto", fileDescriptor_8e97722440bc80f4) }

var fileDescriptor_8e97722440bc80f4 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x95, 0xda, 0x6c, 0xa5, 0xd2, 0x05, 0x4b, 0xfc, 0x73, 0xa8, 0x3d, 0x68, 0x4f,
	0x09, 0xb4, 0x3e, 0x41, 0x45, 0xf4, 0xa4, 0x25, 0x88, 0x07, 0x2f, 0x25, 0x0d, 0x83, 0x09, 0x66,
	0xff, 0xb8, 0x33, 0x29, 0xe6, 0xe2, 0x5b, 0xf8, 0xbe, 0xb2, 0x9b, 0xa4, 0xa5, 0x7a, 0x9c, 0xef,
	0xfb, 0x7d, 0x3b, 0x33, 0x3b, 0x2c, 0x48, 0x95, 0x10, 0x4a, 0x46, 0x19, 0x24, 0x05, 0x65, 0x69,
	0x06, 0xe9, 0x47, 0xa8, 0x8d, 0x22, 0xc5, 0xbb, 0xb5, 0x73, 0x3e, 0x6a, 0x08, 0xf8, 0x4a, 0x41,
	0x53, 0xae, 0x64, 0xed, 0x4f, 0x6e, 0xd9, 0xe9, 0x03, 0xd0, 0xa3, 0xcb, 0xdd, 0xd9, 0x5c, 0x0c,
	0x9f, 0x25, 0x20, 0xf1, 0x0b, 0xe6, 0x67, 0x44, 0x7a, 0xa5, 0x64, 0x51, 0x05, 0xde, 0xd8, 0x9b,
	0xf6, 0xe2, 0x9e, 0x15, 0x9e, 0x65, 0x51, 0x4d, 0xbe, 0xd9, 0xe8, 0x6f, 0x0a, 0xb5, 0x92, 0x08,
	0x7c, 0xce, 0x8e, 0x0c, 0x68, 0x65, 0x08, 0x03, 0x6f, 0xdc, 0x99, 0xf6, 0x67, 0x67, 0x61, 0xdd,
	0x39, 0xdc, 0xa3, 0x2d, 0x11, 0xb7, 0x24, 0x8f, 0x98, 0xbf, 0x9d, 0x2b, 0x38, 0x18, 0x7b, 0xd3,
	0xfe, 0x6c, 0xd8, 0xc6, 0xee, 0x5b, 0x23, 0xde, 0x31, 0x93, 0x1f, 0x8f, 0x0d, 0xff, 0xbd, 0xc7,
	0x2f, 0x99, 0x4f, 0xb9, 0x00, 0xa4, 0x44, 0x68, 0x37, 0xb2, 0x1f, 0xef, 0x04, 0x3e, 0x62, 0x5d,
	0xa4, 0x84, 0x4a, 0x74, 0x1d, 0xfc, 0xb8, 0xa9, 0xf8, 0x15, 0x3b, 0x46, 0x30, 0x9b, 0x3c, 0x85,
	0x95, 0x4c, 0x04, 0x04, 0x1d, 0xe7, 0xf6, 0x1b, 0xed, 0x29, 0x11, 0xc0, 0x6f, 0xd8, 0x49, 0x8b,
	0x6c, 0xc0, 0xa0, 0x9d, 0xf2, 0xd0, 0x51, 0x83, 0x46, 0x7e, 0xad, 0xd5, 0xc5, 0x8b, 0xbb, 0x44,
	0x58, 0x94, 0x94, 0x81, 0xc1, 0x0a, 0x09, 0x04, 0x36, 0x8b, 0x2c, 0x06, 0xdb, 0x4d, 0x96, 0xf6,
	0xe7, 0x97, 0xde, 0xdb, 0xf5, 0x7b, 0x4e, 0x59, 0xb9, 0xb6, 0x40, 0xb4, 0x17, 0x89, 0xdc, 0x6d,
	0x30, 0xaa, 0x93, 0xeb, 0xae, 0x2b, 0xe7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x2c, 0xbc,
	0x2d, 0xe6, 0x01, 0x00, 0x00,
}
