// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: pdfserv/pdfserv.proto

package pdfserv

import (
	common "github.com/luthersystems/protos/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generate a PDF by passing base64 bytes of an html document.
type GenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The base64 string of the html to render as PDF.
	HtmlBase64 string `protobuf:"bytes,1,opt,name=html_base64,json=htmlBase64,proto3" json:"html_base64,omitempty"`
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pdfserv_pdfserv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pdfserv_pdfserv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_pdfserv_pdfserv_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetHtmlBase64() string {
	if x != nil {
		return x.HtmlBase64
	}
	return ""
}

// Response to PDF generation.
type GenerateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An exception if an error occurred during processing request.
	Exception *common.Exception `protobuf:"bytes,1,opt,name=exception,proto3" json:"exception,omitempty"`
	// Base64 encoded PDF generated from the request.
	PdfBase64 string `protobuf:"bytes,2,opt,name=pdf_base64,json=pdfBase64,proto3" json:"pdf_base64,omitempty"`
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pdfserv_pdfserv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pdfserv_pdfserv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_pdfserv_pdfserv_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetException() *common.Exception {
	if x != nil {
		return x.Exception
	}
	return nil
}

func (x *GenerateResponse) GetPdfBase64() string {
	if x != nil {
		return x.PdfBase64
	}
	return ""
}

var File_pdfserv_pdfserv_proto protoreflect.FileDescriptor

var file_pdfserv_pdfserv_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x64, 0x66, 0x73, 0x65, 0x72, 0x76, 0x2f, 0x70, 0x64, 0x66, 0x73, 0x65, 0x72,
	0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x64, 0x66, 0x73, 0x65, 0x72, 0x76,
	0x1a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x68,
	0x74, 0x6d, 0x6c, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x74, 0x6d, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x62, 0x0a, 0x10,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x78, 0x63,
	0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x64, 0x66, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x64, 0x66, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34,
	0x42, 0x54, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x6c, 0x75, 0x74, 0x68, 0x65, 0x72, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x64, 0x66, 0x73, 0x65, 0x72, 0x76, 0x42, 0x0c, 0x50,
	0x44, 0x46, 0x53, 0x65, 0x72, 0x76, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x74, 0x68, 0x65, 0x72,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70,
	0x64, 0x66, 0x73, 0x65, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pdfserv_pdfserv_proto_rawDescOnce sync.Once
	file_pdfserv_pdfserv_proto_rawDescData = file_pdfserv_pdfserv_proto_rawDesc
)

func file_pdfserv_pdfserv_proto_rawDescGZIP() []byte {
	file_pdfserv_pdfserv_proto_rawDescOnce.Do(func() {
		file_pdfserv_pdfserv_proto_rawDescData = protoimpl.X.CompressGZIP(file_pdfserv_pdfserv_proto_rawDescData)
	})
	return file_pdfserv_pdfserv_proto_rawDescData
}

var file_pdfserv_pdfserv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pdfserv_pdfserv_proto_goTypes = []interface{}{
	(*GenerateRequest)(nil),  // 0: pdfserv.GenerateRequest
	(*GenerateResponse)(nil), // 1: pdfserv.GenerateResponse
	(*common.Exception)(nil), // 2: common.Exception
}
var file_pdfserv_pdfserv_proto_depIdxs = []int32{
	2, // 0: pdfserv.GenerateResponse.exception:type_name -> common.Exception
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pdfserv_pdfserv_proto_init() }
func file_pdfserv_pdfserv_proto_init() {
	if File_pdfserv_pdfserv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pdfserv_pdfserv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pdfserv_pdfserv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pdfserv_pdfserv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pdfserv_pdfserv_proto_goTypes,
		DependencyIndexes: file_pdfserv_pdfserv_proto_depIdxs,
		MessageInfos:      file_pdfserv_pdfserv_proto_msgTypes,
	}.Build()
	File_pdfserv_pdfserv_proto = out.File
	file_pdfserv_pdfserv_proto_rawDesc = nil
	file_pdfserv_pdfserv_proto_goTypes = nil
	file_pdfserv_pdfserv_proto_depIdxs = nil
}
