name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      # TODO: re-enable after main merge
      #- uses: bufbuild/buf-breaking-action@v1
      #  with:
      #    against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
